### ISSUE TITLE
Incorrectly detecting fullscreen windows to decide whether or not to hide Taskbar

### ISSUE THREAD

**Issue by jameszhan9592** [lawand-dot-io/taskbar#40]
**Describe the bug**
After activating full screen mode for a video, either from the browser or from a video app (e.g. IINA), Taskbar will stay on screen, covering up part of the full-screen content.

**To Reproduce**
1. Go to YouTube in Safari and play a video (or, open a video file in QT or IINA)
2. Double click the video to full screen it
3. See error

**Expected behavior**
After activating full screen mode for a video, Taskbar should automatically hide.

**Screenshots**
Here's a screen recording demonstrating the issue.
https://github.com/lawand-dot-io/taskbar/assets/76667111/08d44eb5-fb7d-4145-a806-a5508e913321

**Desktop (please complete the following information):**
 - Taskbar version 1.0.8
 - OS: 14.2.1
 - Chip: Apple M1 Max

**Comment by Anthropos888** [comment]
Same with games on MacOS 14 using Heroic Games Launcher / Wine. 
The default MacOS dock would auto hide when starting a game in full screen. The Taskbar doesn't hide.

So you need to rightclick the Taskbar -> "Hide" in order to hide it.
After returning from full screen back to the desktop you need to click the Taskbar-Icon in the top menu -> "Show" in order to show it again.

**Comment by lawand-dot-io** [comment]
This bug has been fixed in Taskbar version 1.2.1 which is now released. Closing the ticket.
